export type Difficulty = "easy" | "medium" | "hard" | "expert";

export interface WordPack {
  id: string;
  name: string;
  difficulty: Difficulty;
  words: string[];
}

export const WORD_PACKS: WordPack[] = [
  // ──────────────────────────── EASY ────────────────────────────
  {
    id: "easy-1",
    name: "Everyday Objects",
    difficulty: "easy",
    words: [
      "chair", "table", "window", "door", "phone", "book", "lamp", "clock",
      "mirror", "pillow", "blanket", "cup", "plate", "fork", "spoon",
      "knife", "bottle", "bag", "shoe", "hat", "shirt", "pants", "belt",
      "ring", "watch", "key", "lock", "pen", "paper", "envelope",
      "stamp", "coin", "wallet", "umbrella", "candle", "towel", "soap",
      "brush", "comb", "scissors", "needle", "button", "zipper", "pocket",
      "drawer", "shelf", "carpet", "curtain", "fence", "roof",
      "chimney", "stairs", "elevator", "bench", "basket", "bucket",
      "ladder", "wheel", "chain", "rope", "nail", "hammer", "glue",
      "tape", "box", "lid", "handle", "switch", "plug", "wire",
      "battery", "remote", "screen", "speaker", "camera", "frame",
      "vase", "pot", "pan", "oven", "fridge", "sink", "tap",
      "sponge", "broom", "mop", "trash", "bin", "lighter", "match",
      "hook", "hanger", "rack", "tray", "bowl", "jar", "straw",
      "napkin", "tissue", "alarm", "bell",
    ],
  },
  {
    id: "easy-2",
    name: "Animals & Nature",
    difficulty: "easy",
    words: [
      "dog", "cat", "bird", "fish", "horse", "cow", "pig", "sheep",
      "chicken", "duck", "rabbit", "mouse", "frog", "snake", "turtle",
      "bear", "wolf", "fox", "deer", "lion", "tiger", "elephant",
      "monkey", "giraffe", "zebra", "penguin", "dolphin", "whale",
      "shark", "butterfly", "bee", "ant", "spider", "snail", "worm",
      "tree", "flower", "grass", "leaf", "branch", "root", "seed",
      "bush", "forest", "jungle", "desert", "mountain", "river", "lake",
      "ocean", "beach", "island", "cave", "rock", "sand", "mud",
      "rain", "snow", "cloud", "storm", "wind", "sun", "moon",
      "star", "rainbow", "thunder", "ice", "fire", "smoke", "fog",
      "wave", "waterfall", "volcano", "cliff", "valley", "hill",
      "field", "meadow", "pond", "swamp", "coral", "mushroom", "cactus",
      "oak", "pine", "palm", "rose", "tulip", "daisy", "sunflower",
      "eagle", "owl", "parrot", "crow", "swan", "flamingo", "peacock",
      "gorilla", "panda", "koala", "kangaroo",
    ],
  },
  {
    id: "easy-3",
    name: "Food & Drinks",
    difficulty: "easy",
    words: [
      "bread", "butter", "cheese", "milk", "egg", "rice", "pasta",
      "pizza", "burger", "sandwich", "soup", "salad", "cake", "cookie",
      "chocolate", "candy", "ice cream", "pie", "pancake", "waffle",
      "cereal", "toast", "jam", "honey", "sugar", "salt", "pepper",
      "ketchup", "mustard", "vinegar", "oil", "flour", "dough",
      "apple", "banana", "orange", "grape", "lemon", "strawberry",
      "watermelon", "peach", "cherry", "pineapple", "coconut", "mango",
      "tomato", "potato", "onion", "carrot", "corn", "cucumber",
      "lettuce", "broccoli", "mushroom", "garlic", "ginger", "bean",
      "pea", "olive", "avocado", "chili", "pumpkin", "spinach",
      "steak", "chicken", "bacon", "sausage", "ham", "shrimp",
      "lobster", "salmon", "tuna", "crab", "noodle", "dumpling",
      "taco", "burrito", "sushi", "pretzel", "popcorn", "chips",
      "cracker", "donut", "muffin", "brownie", "pudding", "yogurt",
      "coffee", "tea", "juice", "soda", "water", "lemonade", "smoothie",
      "milkshake", "wine", "beer", "cocktail",
    ],
  },
  // ──────────────────────────── MEDIUM ──────────────────────────
  {
    id: "medium-1",
    name: "Actions & Activities",
    difficulty: "medium",
    words: [
      "juggling", "surfing", "climbing", "skiing", "skating", "diving",
      "fishing", "camping", "hiking", "gardening", "painting", "sculpting",
      "knitting", "sewing", "cooking", "baking", "grilling", "brewing",
      "whistling", "yawning", "sneezing", "coughing", "stretching",
      "meditation", "yoga", "boxing", "wrestling", "fencing", "archery",
      "bowling", "billiards", "darts", "chess", "puzzle", "karaoke",
      "photography", "astronomy", "origami", "calligraphy", "pottery",
      "embroidery", "woodworking", "blacksmithing", "weaving", "tattooing",
      "smuggling", "eavesdropping", "sleepwalking", "daydreaming",
      "brainstorming", "negotiation", "debate", "auction", "interview",
      "audition", "rehearsal", "performance", "marathon", "triathlon",
      "paragliding", "bungee jumping", "skydiving", "rafting", "kayaking",
      "snorkeling", "scuba diving", "windsurfing", "horseback riding",
      "mountain biking", "rock climbing", "ice skating", "snowboarding",
      "sledding", "tobogganing", "trampolining", "parkour", "gymnastics",
      "weightlifting", "sprinting", "hurdles", "javelin", "discus",
      "pole vault", "high jump", "long jump", "shot put", "decathlon",
      "trivia", "charades", "pantomime", "impersonation", "ventriloquism",
      "tightrope walking", "sword swallowing", "fire breathing",
      "escapology", "hypnosis", "fortune telling", "arm wrestling",
      "thumb war", "hopscotch",
    ],
  },
  {
    id: "medium-2",
    name: "Professions & Roles",
    difficulty: "medium",
    words: [
      "detective", "astronaut", "surgeon", "architect", "journalist",
      "diplomat", "archaeologist", "librarian", "pharmacist", "veterinarian",
      "electrician", "plumber", "carpenter", "mechanic", "firefighter",
      "paramedic", "lifeguard", "referee", "coach", "conductor",
      "pilot", "navigator", "captain", "admiral", "general",
      "ambassador", "senator", "mayor", "governor", "president",
      "judge", "lawyer", "prosecutor", "accountant", "economist",
      "philosopher", "psychologist", "therapist", "dentist", "optician",
      "barista", "bartender", "sommelier", "florist", "jeweler",
      "tailor", "butcher", "baker", "locksmith", "watchmaker",
      "translator", "interpreter", "curator", "auctioneer", "appraiser",
      "choreographer", "director", "producer", "screenwriter", "editor",
      "illustrator", "animator", "cartographer", "meteorologist",
      "geologist", "biologist", "chemist", "physicist", "mathematician",
      "programmer", "hacker", "spy", "bounty hunter", "bodyguard",
      "sheriff", "ranger", "warden", "janitor", "butler",
      "nanny", "midwife", "undertaker", "gravedigger", "blacksmith",
      "shepherd", "lumberjack", "miner", "diver", "stuntman",
      "acrobat", "magician", "clown", "puppeteer", "taxidermist",
      "beekeeper", "falconer", "gladiator", "samurai", "knight",
    ],
  },
  {
    id: "medium-3",
    name: "Places & Landmarks",
    difficulty: "medium",
    words: [
      "lighthouse", "cathedral", "monastery", "pyramid", "colosseum",
      "amphitheater", "aqueduct", "fortress", "dungeon", "tower",
      "skyscraper", "observatory", "planetarium", "aquarium", "zoo",
      "greenhouse", "warehouse", "factory", "windmill", "watermill",
      "harbor", "dock", "pier", "marina", "shipyard",
      "airport", "runway", "hangar", "terminal", "station",
      "subway", "tunnel", "bridge", "dam", "reservoir",
      "fountain", "monument", "statue", "obelisk", "arch",
      "cemetery", "mausoleum", "crypt", "chapel", "mosque",
      "synagogue", "temple", "pagoda", "shrine", "altar",
      "casino", "theater", "opera house", "concert hall", "stadium",
      "arena", "racetrack", "gymnasium", "swimming pool", "spa",
      "hotel", "motel", "hostel", "cabin", "cottage",
      "mansion", "palace", "castle", "igloo", "tent",
      "treehouse", "houseboat", "bunker", "barracks", "embassy",
      "courthouse", "prison", "asylum", "orphanage", "hospital",
      "pharmacy", "laboratory", "library", "museum", "gallery",
      "marketplace", "bazaar", "boutique", "arcade", "laundromat",
      "bakery", "brewery", "vineyard", "plantation", "ranch",
      "barn", "silo", "stable", "kennel", "aviary",
    ],
  },
  // ──────────────────────────── HARD ────────────────────────────
  {
    id: "hard-1",
    name: "Abstract & Concepts",
    difficulty: "hard",
    words: [
      "freedom", "justice", "democracy", "tyranny", "revolution",
      "evolution", "gravity", "infinity", "paradox", "dilemma",
      "irony", "sarcasm", "nostalgia", "melancholy", "euphoria",
      "anxiety", "paranoia", "empathy", "sympathy", "apathy",
      "ambition", "greed", "envy", "jealousy", "pride",
      "humility", "courage", "cowardice", "loyalty", "betrayal",
      "revenge", "forgiveness", "redemption", "sacrifice", "temptation",
      "fate", "destiny", "karma", "luck", "coincidence",
      "chaos", "harmony", "balance", "entropy", "momentum",
      "inertia", "friction", "tension", "pressure", "resistance",
      "illusion", "hallucination", "intuition", "instinct", "reflex",
      "conscience", "consciousness", "subconsciousness", "ego", "identity",
      "reputation", "legacy", "heritage", "tradition", "culture",
      "propaganda", "censorship", "corruption", "bureaucracy", "anarchy",
      "utopia", "dystopia", "capitalism", "socialism", "feudalism",
      "philosophy", "theology", "mythology", "superstition", "taboo",
      "stigma", "stereotype", "prejudice", "discrimination", "privilege",
      "authority", "hierarchy", "rebellion", "conformity", "individuality",
      "creativity", "imagination", "inspiration", "innovation", "wisdom",
      "ignorance", "curiosity", "skepticism", "cynicism", "optimism",
    ],
  },
  {
    id: "hard-2",
    name: "Science & Technology",
    difficulty: "hard",
    words: [
      "algorithm", "encryption", "blockchain", "satellite", "telescope",
      "microscope", "centrifuge", "turbine", "reactor", "accelerator",
      "superconductor", "semiconductor", "transistor", "capacitor", "resistor",
      "hologram", "laser", "radar", "sonar", "ultrasound",
      "radiation", "isotope", "neutron", "proton", "electron",
      "antimatter", "dark matter", "black hole", "supernova", "nebula",
      "constellation", "asteroid", "comet", "meteor", "eclipse",
      "photosynthesis", "osmosis", "mitosis", "mutation", "genome",
      "chromosome", "DNA", "enzyme", "protein", "antibody",
      "vaccine", "antibiotic", "anesthesia", "prosthetic", "pacemaker",
      "stethoscope", "thermometer", "barometer", "seismograph", "gyroscope",
      "pendulum", "pulley", "lever", "gear", "piston",
      "combustion", "propulsion", "aerodynamics", "hydraulics", "pneumatics",
      "thermostat", "alternator", "generator", "transformer", "dynamo",
      "frequency", "wavelength", "amplitude", "resonance", "spectrum",
      "prism", "lens", "fiber optics", "cathode", "anode",
      "electrolysis", "distillation", "fermentation", "crystallization", "sublimation",
      "erosion", "fossilization", "petrification", "calcification", "oxidation",
      "alloy", "polymer", "ceramic", "graphene", "nanotechnology",
      "artificial intelligence", "virtual reality", "augmented reality", "quantum computing", "robotics",
    ],
  },
  {
    id: "hard-3",
    name: "History & Culture",
    difficulty: "hard",
    words: [
      "gladiator", "pharaoh", "emperor", "crusade", "inquisition",
      "renaissance", "enlightenment", "colonialism", "prohibition", "suffrage",
      "guillotine", "catapult", "trebuchet", "chariot", "galleon",
      "musket", "cannon", "bayonet", "trench", "barricade",
      "hieroglyphics", "cuneiform", "alphabet", "printing press", "telegraph",
      "gramophone", "typewriter", "abacus", "compass", "sundial",
      "alchemy", "astrology", "oracle", "prophecy", "ritual",
      "coronation", "abdication", "exile", "amnesty", "treaty",
      "alliance", "embargo", "blockade", "siege", "armistice",
      "espionage", "assassination", "coup", "mutiny", "uprising",
      "pilgrimage", "expedition", "conquest", "migration", "diaspora",
      "famine", "plague", "epidemic", "quarantine", "asylum",
      "aristocracy", "peasantry", "serfdom", "slavery", "emancipation",
      "constitution", "amendment", "parliament", "monarchy", "republic",
      "imperialism", "nationalism", "patriotism", "isolationism", "globalization",
      "communism", "fascism", "totalitarianism", "dictatorship", "oligarchy",
      "renaissance", "baroque", "romanticism", "impressionism", "surrealism",
      "cubism", "minimalism", "modernism", "postmodernism", "avant-garde",
      "samurai", "viking", "spartan", "aztec", "mayan",
      "celtic", "ottoman", "byzantine", "medieval", "industrial revolution",
    ],
  },
  // ──────────────────────────── EXPERT ──────────────────────────
  {
    id: "expert-1",
    name: "Rare & Unusual",
    difficulty: "expert",
    words: [
      "serendipity", "ephemeral", "quintessence", "juxtaposition", "metamorphosis",
      "synesthesia", "schadenfreude", "wanderlust", "zeitgeist", "kindergarten",
      "doppelganger", "poltergeist", "labyrinth", "pandemonium", "catastrophe",
      "phenomenon", "conundrum", "enigma", "fiasco", "debacle",
      "crescendo", "diminuendo", "staccato", "vibrato", "falsetto",
      "silhouette", "camouflage", "mirage", "vertigo", "claustrophobia",
      "arachnophobia", "kleptomania", "pyromania", "insomnia", "amnesia",
      "déjà vu", "faux pas", "carte blanche", "coup de grâce", "tour de force",
      "magnum opus", "modus operandi", "persona non grata", "quid pro quo", "status quo",
      "terra incognita", "tabula rasa", "ad nauseam", "bona fide", "carpe diem",
      "flamboyant", "extravagant", "ostentatious", "pretentious", "audacious",
      "nonchalant", "mellifluous", "cacophony", "onomatopoeia", "palindrome",
      "oxymoron", "hyperbole", "metaphor", "allegory", "euphemism",
      "soliloquy", "monologue", "rhetoric", "eloquence", "vernacular",
      "bureaucracy", "meritocracy", "plutocracy", "kleptocracy", "theocracy",
      "sovereignty", "hegemony", "autonomy", "diplomacy", "technocracy",
      "philanthropy", "misanthropy", "claustrophobia", "agoraphobia", "xenophobia",
      "clairvoyance", "telekinesis", "telepathy", "premonition", "apparition",
      "purgatory", "limbo", "oblivion", "eternity", "immortality",
      "resurrection", "reincarnation", "transcendence", "enlightenment", "nirvana",
    ],
  },
];
